### ISSUE TITLE
Something wrong with discord api idk

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#15]
![20220717_004152](https://user-images.githubusercontent.com/106020383/179373992-e5a3902d-6877-4990-8a55-4c960f9d4599.jpg)

**Comment by Mago126** [comment]
this thing is keep popping up after typing rs

**Comment by ulnk** [comment]
can you provide a video?

**Comment by Mago126** [comment]
> can you provide a video?

tomorrow i have to sleep

**Comment by Mago126** [comment]
Hey what is an Mass message billing?

**Comment by ulnk** [comment]
stop making so many issues for things that are your fault.

**Comment by ulnk** [comment]
i cannot replicate this issue
