### ISSUE TITLE
discord mass dm doesnt work

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#18]
discord mass dm doesnt work ive scanned qr but it didnt mass dm on my acc

**Comment by Mago126** [comment]
![image](https://user-images.githubusercontent.com/106020383/179400103-e8933843-ecef-447d-8027-b0afa5bf8563.png)
this popped up after 2 mins

**Comment by Mago126** [comment]
![image](https://user-images.githubusercontent.com/106020383/179400194-23ac15cf-9579-4c86-b37d-066272ad8e96.png)
popped up again after scanning mass dm needs to get fixed

**Comment by ulnk** [comment]
I will get around to fixing it
