### ISSUE TITLE
Websocket still not fixed with Videos!

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#22]
Recorded on Mobile crashed 3 times after every 2 mins maybe thats because too many people are trying to verify or something i really dont know but this has to get fixed somehow aint no way i have to restart it every 2 mins
https://streamable.com/agyhfr
crashed 9 times while i was uploading this video
heres the video of the crashes https://streamable.com/f2x11b

another video caught the bot crashing
https://streamable.com/vffoy8

Picture of a Different issue about discord api or something 
![20220717_203041](https://user-images.githubusercontent.com/106020383/179419939-9530eba3-ec5c-4293-953e-a139c22a3b06.jpg)

**Comment by Mago126** [comment]
if you cant fix it then do a automatically restarting system everytime when it crashes

**Comment by ulnk** [comment]
damn bruh

**Comment by ulnk** [comment]
i will get on this

**Comment by ulnk** [comment]
@Mago126 are you using the most upadted version

**Comment by Mago126** [comment]
> @Mago126 are you using the most upadted version

im using the updated version with blocking feature

**Comment by Mago126** [comment]
> @Mago126 are you using the most upadted version

ill send a picture of my config.json file

**Comment by Mago126** [comment]
> @Mago126 are you using the most upadted version

![image](https://user-images.githubusercontent.com/106020383/179423856-1932ed4b-78ec-45a0-915f-2d261c7f488d.png)
btw its still crashing every 2 mins for me i got 320 members and they all are trying to verify i think thats why due to the many people trying to verify needs to get fixed somehow

**Comment by ulnk** [comment]
[This Commit](https://github.com/ulnk/scam/commit/0316c25eafb21e6576171b8c44f96777246e8f5b) might've fixed the issue
idk just try

**Comment by Mago126** [comment]
> [This Commit](https://github.com/ulnk/scam/commit/0316c25eafb21e6576171b8c44f96777246e8f5b) might've fixed the issue idk just try

ill try check

**Comment by Mago126** [comment]
> [This Commit](https://github.com/ulnk/scam/commit/0316c25eafb21e6576171b8c44f96777246e8f5b) might've fixed the issue idk just try

hey theres a other issue now 
![image](https://user-images.githubusercontent.com/106020383/179424121-43f4b1ea-334b-40c2-b73d-d658707b6b30.png)

**Comment by Mago126** [comment]
> [This Commit](https://github.com/ulnk/scam/commit/0316c25eafb21e6576171b8c44f96777246e8f5b) might've fixed the issue idk just try

using the new updated files now and this happened 
![image](https://user-images.githubusercontent.com/106020383/179424138-466a187a-f015-4354-b08a-97b4f712e5e3.png)

**Comment by Mago126** [comment]
> [This Commit](https://github.com/ulnk/scam/commit/0316c25eafb21e6576171b8c44f96777246e8f5b) might've fixed the issue idk just try

ive just restarted with "rs" and looks like it works now

**Comment by ulnk** [comment]
```yarn add piscina```

**Comment by Mago126** [comment]
> `yarn add piscina`

used npm add piscina and runned it and now the same issue popped up like before check the picture
![image](https://user-images.githubusercontent.com/106020383/179424285-e0933d39-ca34-49d0-9849-8cfde25839f9.png)

**Comment by Mago126** [comment]
> `yarn add piscina`

C:\Users\Samsu\Desktop\scam4254\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Users\Samsu\Desktop\scam4254\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Samsu\Desktop\scam4254\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ButtonInteraction.reply (C:\Users\Samsu\Desktop\scam4254\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5) {
  method: 'post',
  path: '/interactions/998330772924678154/aW50ZXJhY3Rpb246OTk4MzMwNzcyOTI0Njc4MTU0OkdkUGdVVVgyd1pkejFIbFdHVnZuM1A5NXdGcnd5Zm1VV2J0VmoxdXBlOWowZWRsbjhWTWFpaVJSVEtvdm1JdFFDamNGNDZ5SE9BaUhVUGlMREtkSEVBYzQ4cm16S2hkVmxSN25xcGZwMnJqbjFpc0lFemFZOEtObUdtckphSWp6/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Mago126** [comment]
> `yarn add piscina`

a completely different issue now check the picture used "rs"
![image](https://user-images.githubusercontent.com/106020383/179424358-26fffba8-7782-432a-8465-d3bc2fe909a2.png)

**Comment by Mago126** [comment]
> `yarn add piscina`

used restart  worked and pressed on verify as an test and this thing popped up instantly after pressing verify
![image](https://user-images.githubusercontent.com/106020383/179424395-a76c756b-e5c2-46eb-8cb5-15bcfd99e56e.png)

**Comment by ulnk** [comment]
dm me on discord to continue
its annoying talking here
also for any opther issues dm me

**Comment by Mago126** [comment]
> `yarn add piscina`

whats your discord

**Comment by Mago126** [comment]
> dm me on discord to continue its annoying talking here also for any opther issues dm me

whats your discord

**Comment by Mago126** [comment]
> dm me on discord to continue its annoying talking here also for any opther issues dm me

my discord is Ruler#7425

**Comment by Mago126** [comment]
> dm me on discord to continue its annoying talking here also for any opther issues dm me

whats your discord??
