### ISSUE TITLE
another issue

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#24]
did everything right 
![image](https://user-images.githubusercontent.com/106020383/180864398-78e92451-366c-48a7-bdf7-7dd7805b0292.png)
![image](https://user-images.githubusercontent.com/106020383/180864464-899fec3e-cea5-4f49-a100-dd5c159e81cc.png)

**Comment by ulnk** [comment]
can you read???
stop leaving retarded issues because you can't read. I'll get muwop to shop your ass
rename to config.json

**Comment by Mago126** [comment]
> can you read??? stop leaving retarded issues because you can't read. I'll get muwop to shop your ass rename to config.json

OHHHHH
