### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#3]
everything worked but...

![image](https://user-images.githubusercontent.com/106020383/178219975-f1cf992d-5440-4d55-bd62-1184da40fac2.png)
and in dms it looks like this 
![image](https://user-images.githubusercontent.com/106020383/178220020-9565037f-1883-4ab6-87f2-aff35ca12371.png)
![image](https://user-images.githubusercontent.com/106020383/178220567-0787994b-9435-47c9-9e17-cb7bfda0d4a4.png)
![image](https://user-images.githubusercontent.com/106020383/178220622-94f41cfa-09a8-48fa-a797-74d565711020.png)

**Comment by ulnk** [comment]
* **Add all emojis to server**
  * Without, the emojis will be `undefined`
  * You can select all and drag into the add emojis discord page
  * *(NOTE: YOU HAVE TO ADD ALL EMOJI IDS INTO CONFIG.JSON)*

please read readme
