### ISSUE TITLE
Bozo

### ISSUE THREAD

**Issue by notbeer** [ulnk/scam#30]
Bozos like you are the cause of retarded scams on discord. Could've done something better than fucking making some retarded QR scanning scam 🤦🏽‍♂️

**Comment by ulnk** [comment]
💻 I started programming very recently, so I'm still learning as I go. I'm open to any types of feedbacks!
    🤖 I usually develop random websites, AI's, or random softwares.
    ⚙️ I'm currently learning to work with different types of web app frameworks and TensorFlow.
    📂 I like to contribute to open source projects in any way possible.
    🏀 In my free time, I love to play basketball or watch movies/shows OR animes!
