### ISSUE TITLE
replit error

### ISSUE THREAD

**Issue by rubi72** [ulnk/scam#31]
![image](https://user-images.githubusercontent.com/81889577/186186128-6a6e9a63-04d6-4745-96d1-a40eb1cbe08b.png)

**Comment by kevincrafturu2** [comment]
Same

**Comment by ulnk** [comment]
step 1; dont use replit and follow readme steps

**Comment by kevincrafturu2** [comment]
But why dont use replit, Its the only host free

**Comment by ulnk** [comment]
heroku is free

**Comment by kevincrafturu2** [comment]
You have any link to fork from heroku?

**Comment by rubi72** [comment]
send heroku fork link
