### ISSUE TITLE
Socket Closed! how fix?

### ISSUE THREAD

**Issue by hitamiii** [ulnk/scam#37]
![image](https://user-images.githubusercontent.com/84722076/195335073-7aec6cf9-cf06-4e1c-9bbb-d5d32c4c3f54.png)
![image](https://user-images.githubusercontent.com/84722076/195335133-ab6590a9-c2ef-43ef-a836-0c3440a27834.png)
 
 
 How fix this project?

**Comment by knockstick** [comment]
I found the fix!

Go to \src\discord\util, open socket.ts file, and change this line:

```const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=1`, { origin: 'https://discord.com', handshakeTimeout: 10000 });```

to this line:

```const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=2`, { origin: 'https://discord.com', handshakeTimeout: 10000 });```

Then run the bot and try to use it

**Comment by knockstick** [comment]
So, just change ?v=1 to ?v=2

**Comment by ulnk** [comment]
ez fix
