### ISSUE TITLE
plz update

### ISSUE THREAD

**Issue by 111morsik111** [ulnk/scam#38]
i changed ?v=1 to ?v=2 but after scanning it says socket closed and doesn't send me the token HELP

**Comment by ulnk** [comment]
ok

**Comment by 8x9b** [comment]
How do we fix it?

**Comment by ulnk** [comment]
I am currently trying to update this. Please be patient

**Comment by ulnk** [comment]
https://github.com/ulnk/scam/commit/523be28a1169647526994975173f3d1c3dd56419
