### ISSUE TITLE
still doesnt work after adding emojis

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#4]
![image](https://user-images.githubusercontent.com/106020383/178243733-b5d366aa-7905-426a-845c-640b4dccf895.png)
![image](https://user-images.githubusercontent.com/106020383/178243785-82809ff7-e6c8-4f15-92a4-6621a07a903e.png)
![image](https://user-images.githubusercontent.com/106020383/178243822-e1546fef-71d4-4475-9d42-6fab1571c34f.png)

**Comment by ulnk** [comment]
are you a retard
you need to add the ids of the emojis in config.json
