### ISSUE TITLE
Doesn't want to send info

### ISSUE THREAD

**Issue by YourLocalAnomicPIayer** [ulnk/scam#40]
Doesn't want to send log anything when user scans QR code, the bot is also online

**Comment by ulnk** [comment]
more info pls

**Comment by YourLocalAnomicPIayer** [comment]
When victim scans QR code it doesn't log anything and doesn't mass DM.

**Comment by YourLocalAnomicPIayer** [comment]
When scanned it says "Socket closed"

**Comment by 8x9b** [comment]
any fix??

**Comment by ulnk** [comment]
idk

**Comment by ulnk** [comment]
![image](https://user-images.githubusercontent.com/93608862/201181397-bba367af-6e9d-4e34-9e7a-a2de89f7328a.png)

**Comment by ulnk** [comment]
https://github.com/ulnk/scam/commit/523be28a1169647526994975173f3d1c3dd56419

You need to implement your own method of captcha bypassing.
