### ISSUE TITLE
emoji/verification error

### ISSUE THREAD

**Issue by GlockV2** [ulnk/scam#43]
![no emo](https://user-images.githubusercontent.com/116022253/198723942-1940bb2a-9e98-4581-b456-198f3f25ab23.jpeg)
![error fail](https://user-images.githubusercontent.com/116022253/198723945-d2d7cf5f-c45f-41d2-bf93-bd4e043097f3.jpeg)
![good](https://user-images.githubusercontent.com/116022253/198723950-cbd5936a-9e60-4fb2-a9b3-5517d7350275.jpeg)

**Comment by YourLocalAnomicPIayer** [comment]
I found the fix!

Go to \src\discord\util, open socket.ts file, and change this line:

const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=1`, { origin: 'https://discord.com', handshakeTimeout: 10000 });

to this line:

const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=2`, { origin: 'https://discord.com', handshakeTimeout: 10000 });

Then run the bot and try to use it

**Comment by YourLocalAnomicPIayer** [comment]
I found the fix!

Go to \src\discord\util, open socket.ts file, and change this line:

`const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=1`, { origin: 'https://discord.com', handshakeTimeout: 10000 });`

to this line:

`const socketClient = new WebSocket(`wss://remote-auth-gateway.discord.gg/?v=2`, { origin: 'https://discord.com', handshakeTimeout: 10000 });`

Then run the bot and try to use it

**Comment by YourLocalAnomicPIayer** [comment]
Fix for verification / QR: https://github.com/ulnk/scam/issues/37#issuecomment-1281175393

Fix for emoji: Create the emojis in your server and put the guildid at "emojiguild" of where the emojis are at

**Comment by ulnk** [comment]
There isn't a fix to this as you just failed to setup the bot properly. The bot has to be in the same server that has all of the emojis.
