### ISSUE TITLE
No file named "config-default.json"

### ISSUE THREAD

**Issue by DARKNOSY** [ulnk/scam#44]
In one step, we have to modify the name of the file: "**_config-default.json_**" but there isn't one, unless I'm blind
![screenshot wick scam](https://user-images.githubusercontent.com/109553205/201368071-26cb144b-5c7b-467c-8613-08b13df95e78.png)

**Comment by ulnk** [comment]
**Issue Resolved**
https://github.com/ulnk/scam/commit/e0aeee37ba5966580ee58596cd8f2e57adc2f006 In this commit I accidently removed it. I have have added it back.

**Comment by DARKNOSY** [comment]
ok thanks
