### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Potttential** [ulnk/scam#45]
when trying to scan the code, the token does not come

**Comment by ulnk** [comment]
Can you provide more information. Like screenshots of the console, and how you set it up.

**Comment by ulnk** [comment]
Also staring the project will make me more motivated to fix errors

**Comment by Potttential** [comment]
![image](https://user-images.githubusercontent.com/118055313/201475141-727c8732-b6c5-4e03-9b5b-c26a8a921d53.png)

**Comment by Potttential** [comment]
This error crashes every time, I will assume that you need to add anti-captcha

**Comment by ulnk** [comment]
Anti captcha is needed

**Comment by boumco** [comment]
Same error

**Comment by ulnk** [comment]
# Issue Resolved
https://github.com/ulnk/scam/commit/a4b03145aa7fff2f9dc0edd3daefecd32742a0ec Fixes this issue. Please redownload the latest version
