### ISSUE TITLE
I'm wondering?

### ISSUE THREAD

**Issue by unintends** [ulnk/scam#5]
If you think this really is how is working why when you get the "QR code" it's [ https://media.discordapp.net/attachments/995795316441894912/996024300127658024/img.png ] --> as 995795316441894912 stands for the ID of @ulnk server instead of people right here. This sends me to a "creation" that doesn't help anyone in the community but just  you. Why can't the people set their own QR code? This got my attention when someone noticed it. So if you really are so transparent could the owner of this repository [ @ulnk ] explain why is it like that, and why can't we set our own QR code?

**Comment by ulnk** [comment]
what.
the qr code url is:
```ts
const fingerprintData = `https://discordapp.com/ra/${data.fingerprint}`;
const qrCodeURL = `https://api.qrserver.com/v1/create-qr-code/?size=256x256&data=${fingerprintData}`;
```
this is not specific for any server. it is connected to a websocket and when the user scans it, the websocket will receive the token.
