### ISSUE TITLE
Bot Quarantined instantly

### ISSUE THREAD

**Issue by DemonMartin** [ulnk/scam#50]
![img](https://user-images.githubusercontent.com/49092993/205466816-b9bb854f-fdd2-4198-bc0d-da8a6f2c31a5.png)

Bot Quarantined after just testing it out, lol.

Maybe add some kind of option which makes it possible to use "ephemeral" messages in the guild instead of dming the user, since dming the user gets the bot quarantined.

**Comment by ulnk** [comment]
Make it not wick
