### ISSUE TITLE
good but some bugs

### ISSUE THREAD

**Issue by Dinosaurum** [ulnk/scam#51]
Really good tool! But there is a bug:
(tried with 3 different accounts)
![image](https://user-images.githubusercontent.com/96620548/205724553-4f1c2b0b-fadc-4789-8395-e647fcfc8773.png)

EDIT: It is because Discord detects the bot as a spam bot and quarantines it, **just give it another name and choose a google logo that has already been made and looks pretty good**

**Comment by Prophency** [comment]
but there's a bug, I only get this error: (I tried with 3 different accounts)
![image](https://user-images.githubusercontent.com/96620548/205724553-4f1c2b0b-fadc-4789-8395-e647fcfc8773.png)

**Comment by ulnk** [comment]
idk ill get around to fixing it

**Comment by Dinosaurum** [comment]
fixed it ig, just give it another name and find some weird modern logos on google and give it its name but how do I change the rpc?

**Comment by lostroes** [comment]
what captcha are you using for it, it gives me errors with 2captcha

**Comment by Dinosaurum** [comment]
I'm using no captcha, just don't spam it like a little bitch and give it another name with pfp, will work fine then

**Comment by lostroes** [comment]
![image](https://user-images.githubusercontent.com/80589822/206542033-34629eed-eb55-42b0-b007-563fc8814022.png)
i doesn't work for me when you don't have anti captcha

**Comment by ulnk** [comment]
Use dev branch for a more stable captcha service

**Comment by ulnk** [comment]
> fixed it ig, just give it another name and find some weird modern logos on google and give it its name but how do I change the rpc? @ulnk 
> 
> 

Why

**Comment by ulnk** [comment]
to change the rpc it takes a monkey to have a slight glance at the files. 
`ready.ts` there you can change it
