### ISSUE TITLE
DiscordAPIError[10062]: Unknown interaction

### ISSUE THREAD

**Issue by lostroes** [ulnk/scam#53]
![image](https://user-images.githubusercontent.com/80589822/208531027-fcf7e689-da98-43c6-8380-59a01c665a7f.png)

Can someone help with this error?

**Comment by lostroes** [comment]
this is v3

**Comment by ulnk** [comment]
I AM NOT FIXING NOT MY PROBLEM ITS DISCORD JS

**Comment by ulnk** [comment]
**Issue Resolved**
This issue has been fixed in the latest commit: https://github.com/ulnk/scam/commit/9257ac0319fc2c31ee4fd9921c8050c2d9e65d09.

Please post another issue if it occurs again.
