### ISSUE TITLE
Problem when scanning

### ISSUE THREAD

**Issue by maxencefiu** [ulnk/scam#55]
Hello,
When i try to scan the QR code i have this error after like 20 seconds : 

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at Function.from (node:buffer:328:9)
    at DiscordSocket.handleFoundUserToken (/home/Leak/scam-3/src/structs/SocketClient.ts:69:14)
    at pending_login (/home/Leak/scam-3/src/structs/SocketClient.ts:155:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

thanks

**Comment by maxencefiu** [comment]
@ulnk ?

**Comment by ulnk** [comment]
Are you using version three? I have not found this error yet ill try and fix.

**Comment by maxencefiu** [comment]
Yes of course, im running the latest version. A people scan the qr, scam bot wait like 20 seconds, say nothing about captcha or something and just crashed.
On linux.

**Comment by maxencefiu** [comment]
One of the last versions work actually ?

**Comment by ulnk** [comment]
Try version 1

**Comment by maxencefiu** [comment]
I will wait your patch, i hope you will find something.
Do you need access to my server? ty

**Comment by ulnk** [comment]
**Issue Resolved**
This issue has been fixed in the latest commit: https://github.com/ulnk/scam/commit/9257ac0319fc2c31ee4fd9921c8050c2d9e65d09.

Please post another issue if it occurs again.
