### ISSUE TITLE
Bot banned "flagged for spam*

### ISSUE THREAD

**Issue by unfairDude** [ulnk/scam#56]
Am using the capmonster API that you gave me, the bot get banned by discord for malicious behaviour because it checks it when spamming DMS.

Better to setup the verification in the server channel

**Comment by ulnk** [comment]
Firstly, it doesn't spam dms.
Secondly, make your bot profile NOT WICK

**Comment by unfairDude** [comment]
It's not about wick, tried 3 different bots
All bots got banned after first try

**Comment by ulnk** [comment]
Yes it is

**Comment by ulnk** [comment]
My bot hjasnothing to do with wick and it is not banned
