### ISSUE TITLE
Dumb dev

### ISSUE THREAD

**Issue by unfairDude** [ulnk/scam#57]
Fuck you time waster, why don't you fucking test the tool before uploading and wasting people time

**Comment by ulnk** [comment]
What do you mean it litteraly works

**Comment by ulnk** [comment]
**Issue Resolved**
This issue has been fixed in the latest commit: https://github.com/ulnk/scam/commit/9257ac0319fc2c31ee4fd9921c8050c2d9e65d09.
Please post another issue if it occurs again.
