### ISSUE TITLE
hcaptcha invalid-response

### ISSUE THREAD

**Issue by Laqer** [ulnk/scam#58]
hi, i'm getting this error from hcaptcha when i send the captcha response (i didn't get this before):

`
{
  captcha_key: [ 'invalid-response' ],
  captcha_sitekey: 'a9b5fb07-92ff-493f-86fe-352a2803b3df',
  captcha_service: 'hcaptcha',
  captcha_rqdata: 'bliUwOZOk1nw+LdxX0ND38LByRjxGMWfkJ5eEBgdvh1rcoVx9s5yGhNg6u0astgpz7Gcj4MYkxvtBjgyL+WQGwSxSiQMxlgkgVJU9yTlg+FmLb1++lBpM0HcLQHKEfliQesWsaDSmAqGp52bobR92E8IR+TVMHYucVlMfbgc',
  captcha_rqtoken: 'IkZDdDRTZFd3cnJvYXZGYml2SlRtcXJudFBBT3hMc2ExZlphbnBiL0tCVmFZbHluNmtpRmQ4REQ0aUVldEhUWDJNVnIrVUE9PXh4ZTV3cmUyUnRta0x2bloi.Y8ve4A.SdRsgRS8Sfo-FwZKbbYS0KL80Vo'
}
`

**Comment by ulnk** [comment]
yeah not my fault

**Comment by ulnk** [comment]
Unfortunately, I am unable to fix that. That is capmonster being very slow and bad.

**Comment by Laqer** [comment]
this is an actual problem of the code

**Comment by ulnk** [comment]
So how is capmonster failing to solve the captcha my fault?
